[phases.setup]
nixPkgs = ["nodejs", "ruby_3_3"]

[phases.install]
cmds = [
  "bundle install",
  "npm install"
]

[phases.build]
cmds = [
  "bundle exec rails assets:precompile"
]

[start]
cmd = "bundle exec puma -C config/puma.rb"
