services:
  - type: web
    name: aichat-web
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: testaichatbot-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: CLACKY_LLM_API_KEY
        sync: false
      - key: CLACKY_LLM_BASE_URL
        value: https://proxy.clacky.ai
      - key: CLACKY_LLM_MODEL
        value: gemini-2.5-flash
      - key: CLACKY_IMAGE_GEN_MODEL
        value: gemini-2.5-flash
      - key: RAILS_LOG_TO_STDOUT
        value: enabled
      - key: RAILS_SERVE_STATIC_FILES
        value: enabled

databases:
  - name: testaichatbot-db
    plan: free
    databaseName: testaichatbot_db
    user: testaichatbot_db_user
