services:
  - type: web
    name: testaichatbot
    runtime: docker
    region: frankfurt
    plan: free
    branch: main
    
    # Docker build optimization settings
    dockerfilePath: ./Dockerfile
    dockerContext: .
    
    # Health check for faster deploy detection
    healthCheckPath: /
    
    # Auto-deploy settings
    autoDeploy: true
    
    envVars:
      - key: RAILS_ENV
        value: production
      
      - key: SECRET_KEY_BASE
        value: 3776147fc15baac64049526867d80a5e55c0f15cde05768a04bc4e79fd947d3a40960f0dadcc9fde9f05caf5bf2975c10865c1425259ad47c9ae1197c34c375d
      
      - key: RAILS_MASTER_KEY
        value: 2b613643f4594a0977bcb1cb9e5e405db37cbfbcfdb49e779982814b0e6d4ef3
      
      - key: DATABASE_URL
        fromDatabase:
          name: testaichatbot-db
          property: connectionString
      
      - key: LLM_BASE_URL
        value: https://proxy.clacky.ai
      
      - key: LLM_API_KEY
        value: sk-7323d6tiSiegTav55nCL0Q
      
      - key: LLM_MODEL
        value: gpt-4o-mini

databases:
  - name: testaichatbot-db
    databaseName: testaichatbot_db
    user: testaichatbot_db_user
    region: frankfurt
    plan: free
    ipAllowList: []
