# Database configuration for production deployment
# Note: This application uses JSON database (lib/json_database.rb), not ActiveRecord
# Empty production configuration to prevent database connection attempts

production:
  # Using JSON database - no database connection needed
  # All data is stored in db/db.json
